### ISSUE TITLE
How to get EDAX?

### ISSUE THREAD

**Issue by mhmtsarigul** [khaotik/OmegaOthello#2]
Hi there. 

I am also trying to train an agent for othello game. But i cant get EDAX program to try my agent against it. It says "service is closed". Do you know any other measure which i can use to determine level of my agent?

Thanks.

**Comment by khaotik** [comment]
(If I remember right) A program called Zebra (or WinZebra for windows version) is also quite proficient. I'm not quite into Othello, you might find better answer in a right forum.
